### ISSUE TITLE
make available output files from previous model runs 

### ISSUE THREAD

**Issue by iantaylor-NOAA** [iantaylor-NOAA/CAPAM_platoons_SS#1]
[This Google Drive folder](https://drive.google.com/drive/folders/1YTp01_D5YMZw_VZ0NlRQQRzh_TBHsNq8?usp=sharing) contains the .csv files output by these lines:
https://github.com/iantaylor-NOAA/CAPAM_platoons_SS/blob/master/CAPAM_platoons_notes.R#L493-L525
I haven't uploaded the .Rdata files created by these lines
https://github.com/iantaylor-NOAA/CAPAM_platoons_SS/blob/master/CAPAM_platoons_notes.R#L450-L451
but could do so if that would be useful.

@k-doering-NOAA, let me know if you have problems accessing that Google Drive folder (it has been shared with you and Rick) or would like me to add additional materials, such as the raw model output or input files from the individual simulations from that old set of simulation data.

**Comment by k-doering-NOAA** [comment]
Thanks, Ian, I can see the files! I think this is enough info for me for now, but I'll let you know if I need anything else.
